### ISSUE TITLE
how_much has one argument instead of zero.

### ISSUE THREAD

**Issue by NovaRain** [falltergeist/int2ssl#3]
https://github.com/falltergeist/int2ssl/blob/0a9d9cac6db4754caf0a4f0989c2c48eadbd32e2/src/OpcodeAttributes.cpp#L263 It should be 1 instead 0.

**Comment by phobos2077** [comment]
No it's not. The compiler accepts 0 arguments for this one:
```
PARSEEXP(HOW_MUCH, 0);
```

**Comment by phobos2077** [comment]
After looking at the engine I conclude that both the original compiler and the int2ssl are **wrong**, it does takes one argument but I can't figure out what it's for. Since this mistake was from the beginning I think it's best to let this function be to avoid confusion and maintain compatibility with scripts that might've used it somehow.

**Comment by NovaRain** [comment]
how_much is never used in vanilla scripts. I wonder if there's any released mod/TC ever uses it.

**Comment by FakelsHub** [comment]
Аргумент не играет никакой роли, он нужен для корректной работы, иначе скрипт начинает глючит.

>  I wonder if there's any released mod/TC ever uses it.

No, because without an argument, it works with an bug.

**Comment by Syst3mSh0ck** [comment]
I thought the older int2ssl in modderspack 3.5 was unaffected, which makes this a regression?
